#!/usr/bin/env bash
# Build the browser client into web/www/.
#
# Needs the wasm target and a matching wasm-bindgen CLI:
#   rustup target add wasm32-unknown-unknown
#   cargo install wasm-bindgen-cli --version 0.2.128
set -euo pipefail

here="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
client="$(dirname "$here")"
profile="${1:-release}"

echo "building dso-web ($profile)"
cargo build --manifest-path "$here/Cargo.toml" --target wasm32-unknown-unknown \
  $([ "$profile" = release ] && echo --release)

wasm="$client/target/wasm32-unknown-unknown/$profile/dso_web.wasm"

# cargo install puts it in ~/.cargo/bin, which is not always on PATH.
bindgen="$(command -v wasm-bindgen || echo "$HOME/.cargo/bin/wasm-bindgen")"
if [ ! -x "$bindgen" ]; then
  echo "wasm-bindgen not found; install it with:" >&2
  echo "  cargo install wasm-bindgen-cli --version 0.2.128" >&2
  exit 1
fi
# Types are emitted along with the module: the page is checked as
# TypeScript, and these are what tell it what a `Session` can do.
"$bindgen" --target web --out-dir "$here/www/pkg" "$wasm"

# The interpreter's own vocabulary, for the editor's highlighter.
#
# Generated rather than written out by hand so that a name the interpreter
# learns is a name the editor colours: the keywords are the lexer's table and
# the two name lists are the match arms that dispatch them. The editor's
# reference panel is a separate, hand-kept file -- see www/reference.js.
arms() { # the names a `"x" | "y" =>` match arm answers to
  grep -oE '^[[:space:]]*"[a-z0-9_]+"([[:space:]]*\|[[:space:]]*"[a-z0-9_]+")*[[:space:]]*=>' "$1" |
    grep -oE '"[a-z0-9_]+"' | tr -d '"' | sort -u
}
quoted() { sed 's/.*/"&"/' | paste -sd, -; }

{
  echo "// Generated by build.sh from the interpreter's own tables. Do not edit."
  echo "//"
  echo "// KEYWORDS keeps the lexer's spelling; the two name lists are lower-cased,"
  echo "// which is how the highlighter looks a word up -- VBScript does not care"
  echo "// about case and neither does the interpreter."
  echo "export const KEYWORDS: string[] = [$(sed -n '/^keywords! {/,/^}/p' "$client/src/lexer.rs" |
    grep -oE '[A-Za-z]+ =>' | sed 's/ =>//' | sort -u | quoted)];"
  echo "export const BUILTINS: string[] = [$(arms "$client/src/builtins/mod.rs" | quoted)];"
  echo "export const API: string[] = [$(arms "$client/src/game/mod.rs" | quoted)];"
} > "$here/www/words.ts"
echo "wrote the editor's vocabulary"

# The shipped player directory, which the client loads into its filesystem at
# startup. `stamp.ts` writes the manifest that names these, since only it
# knows the URL each ends up served at.
#
# Every file, not just *.ds: the READMEs are what bring /downloads and
# /home/music into being, and a console starts in /home, so filtering them out
# left it pointing at a directory that did not exist. The remote filesystem's
# .run and .password files are game content too.
scripts_src="$client/user"
scripts_out="$here/www/scripts"
rm -rf "$scripts_out"
if [ -d "$scripts_src" ]; then
  while IFS= read -r file; do
    rel="${file#"$scripts_src"}"
    mkdir -p "$scripts_out$(dirname "$rel")"
    cp "$file" "$scripts_out$rel"
  done < <(find "$scripts_src" -type f | sort)
  echo "bundled $(find "$scripts_out" -type f | wc -l) files"
fi

# The page itself: TypeScript sources in www/, compiled in place to the
# modules the browser loads. Both projects emit into www/ -- the worker's
# globals and the page's cannot be in scope at once, so they are checked
# separately.
echo "compiling the page"
npm --prefix "$here" run --silent build:ts

# The served copy. Every asset is named for the hash of what is in it, so a
# URL means one file of one build and a deploy can never leave a browser
# holding half of the last one. www/ keeps the sources and the intermediates.
node "$here/stamp.ts"

echo "built into $here/dist"
