
Dim props, propsforexamples
props = "{green 12 underline}"
propsforexamples = "{lgreen 12}"

    Select Case sP
    Case "help"
        Say props & "Command: HELP"
        Say "{lgrey}Display the available console commands."
    Case "restart"
        Say props & "Command: RESTART"
        Say "{lgrey}Restart the console immediately."
    Case "listcolors"
        Say props & "Command: LISTCOLORS"
        Say "{lgrey}Display the available colors and color codes in the console."
    Case "listkeys"
        Say props & "Command: LISTKEYS"
        Say "{lgrey}Display the available shortcut keys and their actions in the console."
    
    Case "time"
        Say props & "Command: TIME"
        Say "{lgrey}Display the current system time."
    Case "date"
        Say props & "Command: DATE"
        Say "{lgrey}Display the current system date."
    Case "now"
        Say props & "Command: NOW"
        Say "{lgrey}Display the current system date and time."
    Case "clear"
        Say props & "Command: CLEAR"
        Say "{lgrey}Clear the console screen."
    Case "stats"
        Say props & "Command: STATS"
        Say "{lgrey}Display active information about the Dark Signs Network."
        Say "{lorange}This information will be shown in the COMM window."
    
    Case "dir"
        
        Say props & "Command: DIR optional-filter"
        Say "{lgrey}Display files and folders in the active directory."
        Say "{lgrey}A filter can be appended to show only elements containing the filter keyword in their name."
        
    Case "pause"
        Say props & "Command: PAUSE optional-msg"
        Say propsforexamples & "Example #1: PAUSE Press a key!"
        Say "{lgrey}Pause the console interface until the user presses a key."
    Case "cd"
        Say props & "Command: CD directory-name"
        Say propsforexamples & "Example #1: CD myfiles"
        Say "{lgrey}Change the active path to the specified directory."
    Case "rd"
        Say props & "Command: RD directory-name"
        Say propsforexamples & "Example #1: RD myfiles"
        Say "{lgrey}Delete the directory with the specified name."
        Say "{lorange}The directory must be empty, or it will not be deleted."
    Case "del"
        Say props & "Command: DEL filename"
        Say propsforexamples & "Example #1: DEL file.ds"
        Say "{lgrey}Delete the specified file or files."
        Say "{lgrey}The wildcard symbol, *, can be used to delete multiple files at once."
        Say "{lorange}Files in the system directory cannot be deleted."
        Say "{orange}Be careful not to delete all of your files!"
        
    Case "md"
        Say props & "Command: MD directory-name"
        Say propsforexamples & "Example #1: MD myfiles"
        Say "{lgrey}Create a new empty directory with the specified name."
        Say "{lorange}The name of the directory should not contain space characters."
            
    Case "lookup"
        Say props & "Command: LOOKUP domain-or-username"
        Say propsforexamples & "Example #1: LOOKUP website.com"
        Say propsforexamples & "Example #2: LOOKUP jsmith"
        Say "{lgrey}View information about the specified domain name or user account."
        Say "{lgrey}This command can be used on both domain names and user accounts."
        Say "{lorange}Data will be returned in the COMM window."
                   
    Case "username"
        Say props & "Command: USERNAME your-username"
        Say propsforexamples & "Example #1: USERNAME jsmith"
        Say "{lgrey}Set or change your Dark Signs username."
        Say "{lorange}If your username and password are invalid or not set, the majority of features will be disabled."
        Say "{lorange}If you do not have an account, visit the website to create one."
    Case "password"
        Say props & "Command: PASSWORD your-password"
        Say propsforexamples & "Example #1: PASSWORD secret123"
        Say "{lgrey}Set or change your Dark Signs password."
        Say "{lorange}If your username and password are invalid or not set, the majority of features will be disabled."
        Say "{lorange}If you do not have an account, visit the website to create one."
    
    Case "ping"
        Say props & "Command: PING domain-or-ip-server"
        Say propsforexamples & "Example #1: PING birds.com"
        Say "{lgrey}Check if the specified server exist on the network."
        Say "{lorange}You can modify this command in the file /system/commands/ping.ds"
    
    Case "me"
        Say props & "Command: ME"
        Say propsforexamples & "Example #1: ME"
        Say "{lgrey}Do nothing at all!"
        Say "{lorange}This is a useless secret command."
    
    Case "pingport"
        Say props & "Command: PINGPORT domain-or-ip-server 80"
        Say propsforexamples & "Example #1: PINGPORT birds.com 80"
        Say "{lgrey}Check if a script is runnning on the server at the specified port number."
        Say "{lorange}You can modify this command in the file /system/commands/pingport.ds"
            
    Case "getip"
        Say props & "Command: GETIP domain-or-ip-server"
        Say propsforexamples & "Example #1: GETIP birds.com"
        Say "{lgrey}Get the IP address of the specified server."
        Say "{lorange}You can modify this command in the file /system/commands/getip.ds"
            
    Case "getdomain"
        Say props & "Command: GETDOMAIN domain-or-ip-server"
        Say propsforexamples & "Example #1: GETDOMAIN 12.55.192.111"
        Say "{lgrey}Get the domain name of the specified server."
        Say "{lorange}You can modify this command in the file /system/commands/getdomain.ds"
                            
    Case "connect"
        Say props & "Command: CONNECT server port-number [optional-parameters]"
        Say propsforexamples & "Example #1: CONNECT home.com 80"
        Say "{lgrey}Connect to a server domain name or IP address on the specified port."
        Say "{lgrey}If no port number is specified, the default port number is 80."
        Say "{lorange}You must specify the port number if you are including optional parameters."
 
        
            
    Case "move"
        Say props & "Command: MOVE source-file destination-file"
        Say propsforexamples & "Example #1: MOVE myoldfile.ds mynewfile.ds"
        Say propsforexamples & "Example #2: MOVE /home/myoldfile.ds  /home/dir2/mynewfile.ds"
        Say "{lgrey}Rename the specified file."
        Say "{lgrey}You can also move the file to a new directory, as shown in example #2."
        Say "{lorange}File names should not contain space characters."
    Case "rename"
        Say props & "Command: RENAME source-file destination-file"
        Say propsforexamples & "Example #1: MD myoldfile.ds mynewfile.ds"
        Say propsforexamples & "Example #2: MD /home/myoldfile.ds  /home/dir2/mynewfile.ds"
        Say "{lgrey}Rename the specified file."
        Say "{lgrey}You can also move the file to a new directory, as shown in example #2."
        Say "{lorange}File names should not contain space characters."
    Case "copy"
        Say props & "Command: COPY source-file destination-file"
        Say propsforexamples & "Example #1: COPY myoldfile.ds mynewfile.ds"
        Say propsforexamples & "Example #2: COPY /home/myoldfile.ds  /home/dir2/mynewfile.ds"
        Say "{lgrey}Create a copy of the specified file."
        Say "{lgrey}You can also move the file to a new directory, as shown in example #2."
        Say "{lorange}File names should not contain space characters."
    
    Case "saycomm"
        Say props & "Command: SAYCOMM text"
        Say propsforexamples & "Example #1: SAYCOMM Connected to server"
        Say "{lgrey}Display the specified text in the COMM window."
        
    Case "run"
        Say props & "Command: RUN file"
        Say propsforexamples & "Example #1: RUN myscript.ds"
        Say "{lgrey}Run the specified file as script in the console."
        Say "{lgrey}Files not designed to be run as scripts may cause random errors to be displayed."
            
    Case "edit"
        Say props & "Command: EDIT file"
        Say propsforexamples & "Example #1: EDIT myscript.ds"
        Say "{lgrey}Edit the specified file in the editing window. The console will pause while the editor is active."
        Say "{lorange}Files in the editor are saved automatically."
                
'    Case "wait"
'        Say props & "Command: WAIT milliseconds"
'        Say propsforexamples & "Example #1: WAIT 1000"
'        Say "{lgrey}Pause the console for the specific amount of time (between 1 and 60000 ms)."
'        Say "{lorange}1000 millisends is equal to 1 second."
'        Say "{orange}This command is only enabled in scripts."
                    
    Case "upload"
        Say props & "Command: UPLOAD server port-number file"
        Say propsforexamples & "Example #1: UPLOAD mywebsite.com 80 newscript.ds"
        Say "{lgrey}Upload a file to your domain name on the specified port."
        Say "{lgrey}This script will then become connectable to all players."
        Say "{lorange}You can only upload and download scripts to domain names (servers) which you own."
    
    Case "closeport"
        Say props & "Command: CLOSEPORT server port-number"
        Say propsforexamples & "Example #1: CLOSEPORT mywebsite.com 80"
        Say "{lgrey}Close port on the specified domain."
        Say "{lgrey}The script running on this port is deleted."
        Say "{lorange}You can only close ports on domain names (servers) which you own."
                                      
    Case "download"
        Say props & "Command: DOWNLOAD server port-number file"
        Say propsforexamples & "Example #1: DOWNLOAD mywebsite.com 80 thescript.ds"
        Say "{lgrey}Download a script file from a sever that you own."
        Say "{lorange}You can only upload and download scripts to domain names (servers) which you own."
                             
    Case "transfer"
        Say props & "Command: TRANSFER recipient-username amount description"
        Say propsforexamples & "Example #1: TRANSFER admin 5 A payment for you"
        Say "{lgrey}Transfer an amount of money (DS$) to the specified username."
        Say "{lorange}Each transfer requires manual authorization from the sender."
                                    
    Case "ydiv"
        Say props & "Command: YDIV height"
        Say propsforexamples & "Example #1: YDIV 240"
        Say "{lgrey}Change the default space between each console line."
        Say "{lorange}The default YDIV is set to 60."
                                           
    Case "display"
        Say props & "Command: DISPLAY file optional-start-line optional-max-lines"
        Say propsforexamples & "Example #1: DISPLAY myfile.txt 1 5"
        Say "{lgrey}Output the specified file to the console, without running as a script."
        Say "{lorange}In the example, the first five lines of myfile.txt will be displayed."
                                                   
    Case "append"
        Say props & "Command: APPEND file optional-START-or-END text"
        Say propsforexamples & "Example #1: APPEND myfile.txt new data"
        Say propsforexamples & "Example #2: APPEND myfile.txt START new data"
        Say "{lgrey}Append (add) text or data to the specified file."
        Say "{lgrey}Data will be added to the beginning of the file if the START keyword is used."
        Say "{lgrey}Data will be added to the end of the file if the END keyword is used."
        Say "{lorange}If the specified file doesn't exist, it will be created."
                                                           
    Case "write"
        Say props & "Command: WRITE file text"
        Say propsforexamples & "Example #1: WRITE myfile.txt new data"
        Say "{lgrey}Write text or data to the specified file."
        Say "{lorange}If the specified file already exists, it will be overwritten."
        Say "{lorange}Use APPEND to add data to an existing file."
        

    Case "register"
        Say props & "Command: REGISTER domain-name"
        Say propsforexamples & "Example #1: REGISTER mynewwebsite.com"
        Say "{lgrey}Register a domain name on the Dark Signs Network."
        Say "{lgrey}This command requires that you have the required amount of money (DS$) in your account."
        Say "-"
        Say "{center orange nobold 14}- Check the latest prices in the COMM window. -"
        RunPage "domain_register.php?returnwith=2000&prices=1", ConsoleID
        
         
    Case "unregister"
        Say props & "Command: UNREGISTER domain-name account-password"
        Say propsforexamples & "Example #1: UNREGISTER myoldwebsite.com secret123"
        Say "{lgrey}Unregister a domain name that you own on the Dark Signs Network."
        Say "{lorange}This command requires that you include your password for security."
        
            
    Case "login"
        Say props & "Command: LOGIN"
        Say "{lgrey}Attempt to log in to Dark Signs with your account username and password."
        Say "{lgrey}This is only necessary if your status is 'not logged in'."
        Say "{lorange}Use the USERNAME and PASSWORD commands to set or change your username or password."
        
    Case "logout"
        Say props & "Command: LOGOUT"
        Say "{lgrey}Log out of Dark Signs."
        Say "{lgrey}This can be helpful if you want to log in as another user, or if a rare error occurs."
            
    Case "mydomains"
        Say props & "Command: MYDOMAINS"
        Say "{lgrey}List the domain names currently registered to you."
   
    Case "mysubdomains"
        Say props & "Command: MYSUBDOMAINS"
        Say propsforexamples & "Example #1: MYSUBDOMAINS mySite.com"
        Say "{lgrey}List subdomains to a domain that is registed to you."
    
    Case "myips"
        Say props & "Command: MYIPS"
        Say "{lgrey}List all IP addresses registed to you."
     
    Case "music"
        Say props & "Command: MUSIC [parameter]"
        Say propsforexamples & "Example #1: MUSIC NEXT"
        Say "{lgrey}Music parameters are START, STOP, NEXT, and PREV."
        
    Case "say"
        Say props & "Command: SAY text (**optional-properties**)"
        Say propsforexamples & "Example #1: SAY ConsoleID, hello, this is green (**green**)"
        Say propsforexamples & "Example #2: SAY ConsoleID, this is bold and very large (**bold, 36**)"
        Say "{lgrey}Display the specified text in the console."
        Say "{lgrey}Text properties can be modified by adding any number of the following keywords in bewtween (** **), in any order."
        Say "{lgreen}Colors: Type SHOWCOLORS the display a list of colors."
        Say "{lgreen}Fonts: Arial, Arial Black, Comic Sans MS, Courier New, Georgia, Impact,"
        Say "{lgreen}Fonts: Lucida Console, Tahoma, Times New Roman, Trebuchet MS, Verdana, Wingdings."
        Say "{lgreen}Attributes: Bold, NoBold, Italic, NoItalic, Underline, NoUnderline, Strikethru, NoStrikethru."
        Say "{lgreen}Extras: Flash, Flashfast, FlashSlow."
        Say "{orange}Note: You cannot use SAY to display multiple lines of text."
        Say "{orange}For multiple lines, use SAYALL instead."
    
    Case "sayall"
        Say props & "Command: SAYALL text (**optional-properties**)"
        Say propsforexamples & "Example #1: SAYALL hello"
        Say "{lgrey}Same as the SAY command, except will display multiple lines."
        Say "{lorange}Type HELP SAY for more information."
             
    Case "sayline"
        Say props & "Command: SAYLINE text (**optional-properties**)"
        Say propsforexamples & "Example #1: SAYLINE hello"
        Say "{lgrey}Same as the SAY command, except text will be printed on the same line, without moving down."
        Say "{lorange}Type HELP SAY for more information."
           
    Case "remotedelete"
        Say props & "Command: REMOTEDELETE domain filename"
        Say propsforexamples & "Example #1: REMOTEDELETE matrix.com myfile.ds"
        Say "{lgrey}Delete the specified file from the remote server."
        Say "{lorange}You must own the domain, or have subowner privileges on the domain."
    
    Case "remoteupload"
        Say props & "Command: REMOTEUPLOAD domain filename"
        Say propsforexamples & "Example #1: REMOTEUPLOAD matrix.com localfile.ds"
        Say "{lgrey}Upload a file from your local file system to your domain name file system."
        Say "{lorange}You must own the domain, or have subowner privileges on the domain."
           
    Case "remotedir"
        Say props & "Command: REMOTEDIR domain"
        Say propsforexamples & "Example #1: REMOTEDIR matrix.com"
        Say "{lgrey}View files on the remote server."
        Say "{lorange}You must own the domain, or have subowner privileges on the domain."
               
    Case "remoteview"
        Say props & "Command: REMOTEVIEW domain filename"
        Say propsforexamples & "Example #1: REMOTEVIEW google.com userlist.log"
        Say "{lgrey}Display the specified remote file in the console."
        Say "{lorange}You must own the domain, or have subowner privileges on the domain."
    
    Case "draw"
        Say props & "Command: DRAW -y Red(0-255) Green(0-255) Blue(0-255) mode"
        Say propsforexamples & "Example #1: DRAW -1 142 200 11 fadeout"
        Say "{lgrey}Print a background color stream to the console."
        Say "{lgrey}The first parameter, -y, defines the console line."
        Say "{lgrey}For example, -2 will draw to the second line up from the active line."
        Say "{lgrey}The Red, Green, and Blue must be values between 0 and 255."
        Say "{lorange}Available mode keywords: SOLID, FLOW, FADEIN, FADEOUT, FADECENTER, FADEINVERSE."
        Say "{orange}To use custom colors, use the DRAWCUSTOM command."
    
        
    
    Case "subowners"
        Say props & "Command: SUBOWNERS domain-name KEYWORD [optional-username]"
        Say propsforexamples & "Example #1: SUBOWNERS site.com LIST"
        Say propsforexamples & "Example #2: SUBOWNERS site.com ADD friendusername"
        Say propsforexamples & "Example #3: SUBOWNERS site.com REMOVE friendusername"
        Say "{lgrey}Add or remove other user privileges regarding your specified domain name."
        Say "{lgrey}You can add users to this list as subowners of your domain name."
        Say "{lorange}Subowners have permission to interact, upload, and download files from the domain."
        Say "{lorange}Subowners have no ability to unregister or modify the domain name  privileges."
        
        
        
    Case "lineup"
        Say props & "Command: LINEUP"
        Say "{lgrey}Move up an extra console line. Useful for some scripts."
        
     'Case "chatsend"
     '   Say props & "Command: CHATSEND Message to be sent to the chat."
     '   Say propsforexamples & "Example #1: CHATSEND Hello World!"
     '   Say "{lgrey}A simple way to send messages to the chat from your console."
       
    
    Case "chatview"
        Say props & "Command: CHATVIEW [parameter]"
        Say "{lgrey}If set to on, will display chat in the status window."
        Say "{lgrey}CHATVIEW parameters are ON and OFF"

    
    Case Else
        Say props & "Available Commands"
        Say "{lgrey 8}APPEND, CD, CLEAR, CLOSEPORT, CONNECT, COPY, DATE, DEL, DIR, DISPLAY, DOWNLOAD, DRAW, EDIT"
        Say "{lgrey 8}GETIP, GETDOMAIN, LINEUP, LISTCOLORS, LISTKEYS, LOGIN, LOGOUT, LOOKUP, MD, MOVE, MUSIC"
        Say "{lgrey 8}MYDOMAINS, MYIPS, MYSUBDOMAINS, NOW, PASSWORD, PAUSE, PING, PINGPORT, RD, RENAME, REGISTER"
        Say "{lgrey 8}REMOTEDELETE, REMOTEDIR, REMOTEUPLOAD, REMOTEVIEW, RESTART, RUN, SAY, SAYALL, SAYCOMM, STATS"
        Say "{lgrey 8}SUBOWNERS, TIME, TRANSFER, UNREGISTER, UPLOAD, USERNAME, WRITE, YDIV"
        Say "{grey}For more specific help on a command, type: HELP [command]"
    End Select
