<?php

$MYSQL_HOST = 'localhost';
$MYSQL_USERNAME = 'root';
$MYSQL_PASSWORD = '';
$MYSQL_DATABASE = 'darksigns';

$JWT_PUBLIC_KEY = '-----BEGIN PUBLIC KEY-----
PUT YOUR PUBLIC KEY HERE
-----END PUBLIC KEY-----';
$JWT_PRIVATE_KEY = '-----BEGIN PRIVATE KEY-----
PUT YOUR PRIVATE KEY HERE
-----END PRIVATE KEY-----';
