<?php

$DB_HOST = 'localhost';
$DB_USERNAME = 'root';
$DB_PASSWORD = '';
$DB_DATABASE = 'darksigns';

$JWT_PUBLIC_KEY = '-----BEGIN PUBLIC KEY-----
PUT YOUR PUBLIC KEY HERE
-----END PUBLIC KEY-----';
$JWT_PRIVATE_KEY = '-----BEGIN PRIVATE KEY-----
PUT YOUR PRIVATE KEY HERE
-----END PRIVATE KEY-----';

$CAPTCHA_EXPIRY_SECONDS = 300;
$CAPTCHA_WIDTH = 200;
$CAPTCHA_HEIGHT = 50;
$CAPTCHA_LENGTH = 6;
$CAPTCHA_FONT_SIZE = 24;
$CAPTCHA_FONT = '/usr/share/fonts/roboto/Roboto-Regular.ttf';
