#!/bin/sh
set -e

export HOME=/var/lib/caddy
chown -R caddy:caddy "${HOME}"

mkdir -p /run/caddy
chown -R caddy:caddy /run/caddy

tmp_domain="${DOMAIN#http://}"
tmp_domain="${tmp_domain#https://}"
export HTTP_DOMAIN="http://${tmp_domain}"

exec s6-setuidgid caddy /usr/sbin/caddy run --config /etc/caddy/Caddyfile
