#!/bin/sh

# BEGIN Create config.php
PRIVCONF=/run/dso-config.php
touch "${PRIVCONF}"
chown root:php "${PRIVCONF}"
chmod 640 "${PRIVCONF}"

phpenvvar() {
    VAR="${1}"
    eval VAL="\$$VAR"
    echo "\$${VAR} = '${VAL}';" >> "${PRIVCONF}"
}

phpenvvar_b64() {
    VAR="${1}"
    eval VAL="\$$VAR"
    echo "\$${VAR} = base64_decode('${VAL}');" >> "${PRIVCONF}"
}

echo '<?php' > "${PRIVCONF}"

phpenvvar 'DB_HOST'
phpenvvar 'DB_USERNAME'
phpenvvar 'DB_PASSWORD'
phpenvvar 'DB_DATABASE'

phpenvvar_b64 'JWT_PRIVATE_KEY'
phpenvvar_b64 'JWT_PUBLIC_KEY'

phpenvvar 'CAPTCHA_SECRET_KEY'
phpenvvar 'CAPTCHA_FONT'

echo "<?php require_once('${PRIVCONF}');" > /var/www/api/config.php
# END Create config.php

exec /usr/sbin/php-fpm84 --nodaemonize --fpm-config /etc/php-fpm.conf
