#!/bin/sh
set -e

/bin/configure.sh root:php

cp -f /var/www/releases_fallback.json /run/darksignsonline/releases.json
chown php:php /run/darksignsonline/releases.json

exec /usr/sbin/php-fpm84 --nodaemonize --fpm-config /etc/php-fpm.conf
