#!/bin/sh
set -e

mkpriv() {
    privfile="${1}"
    touch "${privfile}"
    chown root:php "${privfile}"
    chmod 640 "${privfile}"
}

# BEGIN Create config.php
PRIVCONF=/run/dso-config.php
mkpriv "${PRIVCONF}"

phpenvvar() {
    VAR="${1}"
    eval VAL="\$$VAR"
    echo "\$${VAR} = '${VAL}';" >> "${PRIVCONF}"
}

phpenvvar_b64() {
    VAR="${1}"
    eval VAL="\$$VAR"
    echo "\$${VAR} = base64_decode('${VAL}');" >> "${PRIVCONF}"
}

echo '<?php' > "${PRIVCONF}"
phpenvvar 'DB_HOST'
phpenvvar 'DB_USERNAME'
phpenvvar 'DB_PASSWORD'
phpenvvar 'DB_DATABASE'
phpenvvar_b64 'JWT_PRIVATE_KEY'
phpenvvar_b64 'JWT_PUBLIC_KEY'
phpenvvar 'CAPTCHA_SECRET_KEY'
phpenvvar 'CAPTCHA_FONT'

echo "<?php require_once('${PRIVCONF}');" > /var/www/api/config.php
# END Create config.php

# BEGIN Create msmtp config
MSMTP_CONF=/run/msmtp.conf
mkpriv "${MSMTP_CONF}"
MSMTP_PASSWD=/run/msmtp.passwd
mkpriv "${MSMTP_PASSWD}"

echo 'defaults' > "${MSMTP_CONF}"
echo 'auth on' >> "${MSMTP_CONF}"
echo 'tls on' >> "${MSMTP_CONF}"
echo 'tls_starttls on' >> "${MSMTP_CONF}"
echo "port 587" >> "${MSMTP_CONF}"
echo 'account default' >> "${MSMTP_CONF}"
echo "host ${SMTP_HOST}" >> "${MSMTP_CONF}"
echo "from ${SMTP_FROM}" >> "${MSMTP_CONF}"
echo "user ${SMTP_USERNAME}" >> "${MSMTP_CONF}"
echo "passwordeval cat '${MSMTP_PASSWD}'" >> "${MSMTP_CONF}"

echo "${SMTP_PASSWORD}" > "${MSMTP_PASSWD}"
# END Create msmtp config

cp -f /var/www/releases_fallback.json /tmp/releases.json
chown php:php /tmp/releases.json

exec /usr/sbin/php-fpm84 --nodaemonize --fpm-config /etc/php-fpm.conf
