// The script API, for the editor's reference panel and for spelling a name
// the way the game does.
//
// One row per procedure the host answers to: its name as the original client
// spells it, and the arguments it takes, with an optional one in brackets.
// The names and signatures are `clsScriptFunctions.cls`, filtered to what
// `game::mod`'s dispatch actually implements -- so a name listed here is one
// a script can call.
//
// The highlighter does not read this table: it matches against the
// lower-cased vocabulary in `words.js`, which is generated from the
// interpreter itself. This one is for the panel, where the casing and the
// argument names are what a player is reading.

export const API: Array<[name: string, args: string]> = [
  ["Append", "file, content"],
  ["ArgC", ""],
  ["ArgV", "number"],
  ["BoolToString", "param"],
  ["Capture", "xarr..."],
  ["CaptureA", "script, [xarr]"],
  ["CaptureCode", "xarr..."],
  ["CaptureCodeA", "code, [xarr]"],
  ["Cat", "file, [startline], [maxlines]"],
  ["CD", "dir"],
  ["ChatSend", "msg"],
  ["ChatView", "enabled"],
  ["CleanupScriptTasks", ""],
  ["Clear", ""],
  ["ClosePort", "domain, port"],
  ["Cls", ""],
  ["Coalesce", "varvalues..."],
  ["CompileStr", "source, [filekey]"],
  ["Connect", "params..."],
  ["ConnectA", "domain, port, [xarr]"],
  ["ConnectingIP", ""],
  ["ConsoleEscape", "tmps"],
  ["ConsoleID", ""],
  ["ConsoleInvisibleChar", ""],
  ["ConsoleUnescape", "tmps"],
  ["ConsoleWidth", ""],
  ["Copy", "source, destination"],
  ["DecodeBase", "text"],
  ["DecodeBase64Bytes", "strdata"],
  ["DecodeBase64Str", "strdata"],
  ["Decrypt", "data, password"],
  ["Del", "file"],
  ["Delete", "file"],
  ["Dir", "path"],
  ["DirExists", "thedir"],
  ["Display", "file, [startline], [maxlines]"],
  ["DLOpen", "library"],
  ["DLOpenHash", "hash"],
  ["DLPutHash", "hash, data"],
  ["DownloadStr", "domain, port"],
  ["Draw", "ypos, rgbval, [mode], [segments]"],
  ["DrawCustom", "ypos, widthsandcolors..."],
  ["DrawCustomA", "ypos, widthsandcolors"],
  ["DrawEven", "ypos, colors..."],
  ["DrawEvenA", "ypos, colors"],
  ["EDIT", "file"],
  ["EncodeBase", "text"],
  ["EncodeBase64Bytes", "xarr"],
  ["EncodeBase64Str", "strdata"],
  ["Encrypt", "data, password, [nowrap]"],
  ["Fetch", "params..."],
  ["FetchA", "domain, port, [xarr]"],
  ["FileExists", "thefile"],
  ["FileLen", "file"],
  ["FormatKB", "toconvert"],
  ["GetASCII", ""],
  ["GetDomain", "ip"],
  ["GetIP", "domain"],
  ["GetKey", ""],
  ["GetMissionData", "missionid, section, key"],
  ["GetMissionFile", "missionid"],
  ["HttpRequest", "url, [postdata]"],
  ["Include", "script"],
  ["IncludeCode", "code"],
  ["IsDomainOnline", "domain"],
  ["IsHex", "hash"],
  ["IsLocal", ""],
  ["IsOutputDisabled", ""],
  ["IsOutputRedirected", ""],
  ["IsPortOpen", "domain, port"],
  ["LineUp", ""],
  ["LOGIN", "[silent]"],
  ["LOGOUT", ""],
  ["Lookup", "domain"],
  ["MAIL", ""],
  ["MD", "newdir"],
  ["Move", "source, destination"],
  ["MUSIC", "command"],
  ["MyDomains", ""],
  ["MyIPs", ""],
  ["MySubdomains", ""],
  ["Overwrite", "file, content"],
  ["Password", ""],
  ["PAUSE", "[prompt], [rgbval]"],
  ["PreSpaceWidth", ""],
  ["PrintVar", "param..."],
  ["PrintVarSingleIfSet", "param"],
  ["Quit", ""],
  ["RD", "olddir"],
  ["ReadDir", "rawpath"],
  ["ReadINI", "file, section, key, value"],
  ["ReadLine", "prompt, [rgbval]"],
  ["Register", "domain"],
  ["RegisterPrices", ""],
  ["RemoteToken", "domain, [info]"],
  ["Rename", "source, destination"],
  ["RequestReadFile", ""],
  ["RequestWriteFile", "data"],
  ["ResolveCommand", "command"],
  ["ResolvePath", "path"],
  ["ResolvePathRel", "basepath, path"],
  ["restart", ""],
  ["RGBJoin", "xarr"],
  ["RGBSplit", "lcolor"],
  ["Run", "xarr..."],
  ["RunA", "script, [xarr]"],
  ["RunCode", "xarr..."],
  ["RunCodeA", "code, [xarr]"],
  ["SafeAppend", "file, text"],
  ["Say", "params..."],
  ["SayCOMM", "params..."],
  ["SayLine", "s, [ypos]"],
  ["ScriptGetOutput", ""],
  ["SendMailToUser", "sfrom, ssubject, smessage"],
  ["ServerDomain", ""],
  ["ServerIP", ""],
  ["ServerPort", ""],
  ["ServerToken", "[info]"],
  ["SetMissionData", "missionid, section, key, value"],
  ["SHA", "text"],
  ["SHA256", "data"],
  ["SpoofLocalConnectingIP", "newvalue"],
  ["Stats", ""],
  ["TextHeight", "text"],
  ["TextWidth", "text"],
  ["Transfer", "target, amount, description"],
  ["TrimWithNewline", "inputstr"],
  ["UnAbort", ""],
  ["Unregister", "domain"],
  ["UploadStr", "domain, port, sfiledata"],
  ["URLEncode", "param"],
  ["UserName", ""],
  ["Wait", "milliseconds"],
  ["WaitFor", "req"],
  ["WaitForRaw", "req"],
  ["Write", "file, text"],
  ["WriteINI", "file, section, key, value"],
  ["yDiv", "setvalue"],
  ["Yield", ""],
];
