on:
  push:
    branches-ignore:
      - main
  workflow_call: {}

concurrency:
  group: server-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' && !startsWith(github.ref, 'refs/tags/') }}

name: Build website container

permissions:
  contents: read
  packages: write

jobs:
  server:
    name: Build website
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - run: ./.github/build-server.sh
