on:
  pull_request: {}
  workflow_call: {}

concurrency:
  group: server-${{ github.ref }}
  cancel-in-progress: true

name: Build server

permissions:
  contents: read

jobs:
  server:
    name: Build server
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v7
    - uses: cachix/install-nix-action@v31
    - name: Build
      run: nix build --print-build-logs .#darksignsonline-server
