on:
  pull_request: {}

concurrency:
  group: server-${{ github.ref }}
  cancel-in-progress: true

name: Build server

permissions:
  contents: read

jobs:
  server:
    name: Build server
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Log in to GitHub Docker Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Build container image
      uses: docker/build-push-action@v6
      with:
        push: false
        build-args: |
          GIT_REVISION=${{ github.sha }}
        tags: ghcr.io/doridian/darksignsonline/server:dev
