on:
  push:
    branches:
      - main

concurrency:
  group: server-publish-${{ github.ref }}
  cancel-in-progress: true

name: Publish server

permissions:
  contents: read
  packages: write

jobs:
  server:
    name: Publish server
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Log in to GitHub Docker Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    - name: Push container image
      uses: docker/build-push-action@v6
      with:
        push: true
        build-args: |
          GIT_REVISION=${{ github.sha }}
        tags: ghcr.io/doridian/darksignsonline/server:latest
