on:
    push:
        branches:
            - main

name: Deploy website

jobs:
  web-deploy:
    name: Deploy website
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: 📂 Sync files
      uses: SamKirkland/FTP-Deploy-Action@v4.3.5
      with:
        server: arcticfox.doridian.net
        username: dsonline
        password: ${{ secrets.FTP_PASSWORD }}
        local-dir: ./server
        server-dir: /public_html
        security: strict
        protocol: ftps
        port: 990
        exclude: |
            **/.git*
            **/.git*/**
            **/mysql_config.php
